name: handspeak
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
    
  flutter_localizations:
    sdk: flutter
  go_router: ^15.1.2
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  google_sign_in: ^6.2.0
  camera: ^0.11.1
  tflite_flutter: ^0.11.0
  firebase_ml_model_downloader: ^0.3.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/registro_ok.png
    - assets/images/alfabeto.png
    - assets/images/animales.png
    - assets/images/comida.png
    - assets/images/google.png
    - assets/images/avatars/avatar1.png
    - assets/images/avatars/avatar2.png
    - assets/images/history_icon.png
    - assets/images/camera_icon.png
    - assets/images/translate_girl.png
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/avatars/avatar1.png"